name: Plugin
version: 1.0
main: de.skobbe.Main

commands:
   heal:
      description: Dieses Kommando heilt dich!
   rename:
      description: Dieses Kommando benennt dich um!
   starterkit:
      description: Dieses Kommando gibt dir ein Starterkit!
   lightning:
      description: Dieses Kommando lässt einen Blitz auf dem Spieler schlagen